routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //$item = new \App\Models\BlogPost();
    //dd($item);

    return view('welcome');
});

Auth::routes();


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');


//Route::resource('rest','RestTestController')->names('restTest');


//Route::group(['namespace'=> 'blog', 'prefix'=>'blog'], function (){
//    Route::resource('posts','PostController')->names('blog.posts');
//});


$groupData = [
    'namespace'  => 'Blog\Admin',
    'prefix'    => 'admin/blog',
];


Route::group($groupData,function (){
    $methods = ['index', 'edit', 'update', 'create', 'store',];
    Route::resource('categories', 'CategoryController')
        ->only($methods)
        ->names('Blog.admin.categories');

    Route::resource('posts','PostController')
        ->names('Blog.admin.posts');
});



Route::get('/user', 'User\UserController@delete');

Route::get('/sitemap.xml','Blog\BlogController@siteMap');

Route::group(['middleware' => ['admin']], function () {
    Route::get('/adminDashboard', 'AdminController@index');
});







Auth::routes();



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Blog/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\BlogCategoryCreateRequest;
use App\Http\Requests\BlogCategoryUpdateRequest;
use App\Models\BlogCategory;
use Illuminate\Http\Request;


class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $item = new BlogCategory();
        $columns = ['id', 'title', 'parent_id'];
        $paginator = $item->select($columns)
                          ->with([
                             'parentCategory:id,title'
                          ])
                          ->paginate(5) ;



        return view('blog.admin.categories.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = new BlogCategory();
        $categorylist = BlogCategory::all();

        return view('blog.admin.categories.edit', compact('item', 'categorylist'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogCategoryCreateRequest $request)
    {
        $data = $request->input();

        $item = new BlogCategory($data);

        $item->save();

        if($item) {
            return redirect()
                ->route('blog.admin.categories.edit', $item->id)
                ->with(['success' => 'успешно сохранено']);
        }else{
            return back()
                ->withErrors(['message' => 'ошибка сохранения'])
                ->withInput();
        }


    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = BlogCategory::findOrFail($id);

        $categorylist = BlogCategory::all();

        return view('blog.admin.categories.edit',
        compact('item','categorylist'));



    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogCategoryUpdateRequest $request, $id)
    {

        $item = BlogCategory::find($id);

        if(empty($item)) {
            return back()
                ->withErrors(['message' =>"запись с id = {{$id}} не найдена"])
                ->withInput();
        }
        $data = $request->all();
        $result = $item
            ->fill($data)
            ->save();

        if($result) {
            return redirect()
                ->route('blog.admin.categories.edit', $item->id)
                ->with(['success' => 'успешно сохранено']);
        }else{
            return back()
                ->withErrors(['message' => 'ошибка сохранения'])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

}

resources/views/blog/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    @php //@var App/Model/BlogCategory $item @endphp

    @if($item->exists)
        <form action="{{route('Blog.admin.categories.update', $item->id)}}" method="POST">
        @method('PATCH')
    @else
        <form action="{{route('Blog.admin.categories.store')}}" method="POST">
    @endif
    @csrf
        <div class="container">
        @php
            /** @var /Illimate/Suppots/ViewErrorBag $errors*/
        @endphp

            @if($errors->any())
           <div class="col-md-12">
            <div class="alert alert-danger" role="alert">

                <button class="btn btn-danger close" data-dismiss="alert">
                    <span aria-hidden="true">close</span>
                </button>
            {{$errors->first()}}
            </div>
           </div>
            @endif

            @if(session('success'))

                <div class="col-md-12">
                    <div class="alert alert-success" role="alert">

                        <button  class="close" data-dismiss="alert">
                            <span aria-hidden="true">close</span>
                        </button>
                        {{session()->get('success')}}
                    </div>
                </div>


            @endif




            <div class="row justify-content-center">

                <div class="col-md-8">

                    @include('blog.admin.categories.includes.item_edit_main_col')


                </div>

                <div class="col-md-3">
{{--                @include('blog.admin.categories.includes.item_edit_add_col')--}}


                </div>

            </div>
    </div>
    </form>
@endsection

resources/views/blog/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <nav class="navbar navbar-toggleable-md navbar-light bd-faded">
                <a href="{{route('Blog.admin.categories.create')}}" class="btn btn-primary">Добавить</a>
            </nav>
        <div class="card">
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Категория</th>
                            <th>Родитель</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($paginator as $item)

                    <tr>
                        <td>{{$item->id}}</td>
                        <td>
                            <a href="{{route('Blog.admin.categories.edit', $item->id)}}">
                                {{$item->title}}
                            </a>
                        </td>
                        <td>
                            {{$item->parentCategory->title}}
                        </td>
                    </tr>
                    @endforeach

                    </tbody>



                </table>
            </div>
        </div>


        </div>
    </div>
</div>

@if($paginator->total() > $paginator->count())
    <br>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {{$paginator->links()}}
                </div>
            </div>
        </div>
        @endif
    </div>
@endsection