routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //$item = new \App\Models\BlogPost();
    //dd($item);

    return view('welcome');
});

Auth::routes();


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');


//Route::resource('rest','RestTestController')->names('restTest');


//Route::group(['namespace'=> 'blog', 'prefix'=>'blog'], function (){
//    Route::resource('posts','PostController')->names('blog.posts');
//});


$groupData = [
    'namespace'  => 'Blog\Admin',
    'prefix'    => 'admin/blog',
];


Route::group($groupData,function (){
    $methods = ['index', 'edit', 'update', 'create', 'store',];
    Route::resource('categories', 'CategoryController')
        ->only($methods)
        ->names('Blog.admin.categories');

    Route::resource('posts','PostController')
        ->names('Blog.admin.posts');
});



Route::get('/user', 'User\UserController@delete');

Route::get('/sitemap.xml','Blog\BlogController@siteMap');

Route::group(['middleware' => ['admin']], function () {
    Route::get('/adminDashboard', 'AdminController@index');
});







Auth::routes();



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Api/Post/PostController.php
<?php

namespace App\Http\Controllers\Api\Post;

use App\Models\BlogPost;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{

    public function getPosts()
    {
        $posts = BlogPost::paginate();
        return response()->json($posts,200);
    }


}

app/Http/Controllers/Blog/Admin/PostController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Http\Requests\BlogPostCreateRequest;
use App\Http\Requests\BlogPostUpdateRequest;
use App\Models\User;
use App\Services\blog\post\PostService;
use App\Http\Controllers\Controller;



class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->only(['create']);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return PostService::indexPost();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return PostService::createrPost();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogPostCreateRequest $request)
    {
        return PostService::storePost($request);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return PostService::showPost($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return PostService::editPost($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogPostUpdateRequest $request, $id)
    {
        return PostService::updatePost($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return PostService::destroyPost($id);
    }



    public function Author()
    {
        return $this->belongsTo(User::class,'user_id','id');
    }





}

resources/views/blog/admin/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    @php//@var App/Model/BlogPost  $item @endphp

        <div class="container">
          @include('blog.admin.posts.includes.result_mes')

            @if($item->exists)
     `          <form method="POST" action="{{route('Blog.admin.posts.update', $item->id)}}">
                    @method('PATCH')
                    @else
                        <form method="POST" action = "{{route('Blog.admin.posts.store')}}">
             @endif
                    @csrf
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('blog.admin.posts.includes.item_edit_main_col')
                </div>

            </div>
        </div>




    </form>

        @if($item->exists)
            <br>
            <form method="POST" action="{{route('Blog.admin.posts.destroy', $item->id)}}">
                @method('DELETE')
                @csrf
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card card-block">
                            <div class="card-body ml-auto">
                                <button class="bnt bnt-link">Удалить</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        @endif









@endsection

resources/views/blog/admin/posts/index.blade.php
@extends('layouts.app')
@php /** @var  $paginate App/Models/BlogPosts */ @endphp
@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
               @include('blog.admin.posts.includes.result_mes')
                <nav class="navbar navbar-toggleable-md navbar-light bd-faded">
                    <a href="{{route('Blog.admin.posts.create')}}" class="btn btn-primary">Добавить новый пост</a>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Автор</th>
                                <th>Краткое описание</th>
                                <th>Категория</th>
                                <th>Заголовок</th>
                                <th>Дата публикаци</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($paginate as $post)
                               <tr @if ($post->is_published) style="background-color: whitesmoke" @endif>
                                   <td>{{$post->id}}</td>
                                   <td>{{$post->user->name}}</td>
                                   <td>{{$post->title}}</td>
                                   <td>{{$post->category->title}}</td>
                                    <td>
                                        <a href="{{route('Blog.admin.posts.edit',$post->id)}}">{{$post->title}}</a>
                                    </td>
                                   <td>{{$post->published_at ? \Carbon\Carbon::parse($post->published_at)->format('d.M H:i') : ''}}</td>
                               </tr>
                            @endforeach

                            </tbody>



                        </table>
                    </div>
                </div>


            </div>
        </div>
    </div>

    @if($paginate->total() > $paginate->count())
        <br>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        {{$paginate->links()}}
                    </div>
                </div>
            </div>
            @endif
        </div>
@endsection